export const STRIPE_PUBLISHABLE_KEY= process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
export const BACKEND_URL= process.env.NEXT_PUBLIC_BACKEND_URL
export const ADMIN_EMAIL = process.env.NEXT_PUBLIC_ADMIN_EMAIL