export const CAR_CATEGORIES = {
    TOYOTA: "TOYOTA",
    HONDA: "HONDA",
    BMW: "BMW",
    MERCEDES: "MERCEDES",
    FORD: "FORD",
    AUDI: "AUDI",
    TESLA: "TESLA",
    BOUGATTI: "BOUGATTI",
    LAMBORGHINI: "LAMBORGHINI",
    FERRARI: "FERRARI",

}as const
